application: cygnan-com
version: 1
runtime: python27
api_version: 1
threadsafe: true

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic

handlers:
- url: /.well-known/acme-challenge/.*
  script: certbot.app

- url: /
  static_files: www/index.html
  upload: www/index.html
  secure: always
  http_headers:
    Strict-Transport-Security: 'max-age=31536000; includeSubDomains; preload'

- url: /
  static_dir: www
  secure: always
  http_headers:
    Strict-Transport-Security: 'max-age=31536000; includeSubDomains; preload'
